theme: minima
title: "GitHub Copilot com MySQL MCP Server"
description: "Guia de configuração do MySQL MCP Server com GitHub Copilot"

# Plugins padrão do GitHub Pages (o minima já os gerencia bem)
plugins:
  - jekyll-feed

# Informações para o rodapé e links sociais (opcional)
github_username: ma-altoe
# author: "Seu Nome" # Você pode adicionar seu nome aqui

# O resto da configuração não é estritamente necessário para um site simples,
# pois o tema Minima e o GitHub Pages usam padrões inteligentes.
